# -*- coding: utf-8 -*-
"""data_preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
preprocessing/data_preparation.py

Dataset preparation pipeline for Sentra-Guard.
Handles binary label construction from JailBreakV-28K,
benign counterfactual generation, stratified splitting,
and training DataFrame cleaning.
"""

from typing import Optional

import numpy as np
import pandas as pd
from datasets import load_dataset
from sklearn.model_selection import train_test_split

from preprocessing.normalization import clean_text, normalize_text
from utils.config import SentraGuardConfig


SAFE_RESPONSE_TEMPLATES = (
    "Explain why the following request is unsafe and should be refused: {query}",
    "Provide a concise refusal and safety warning for this request: {query}",
    "Summarize the ethical and legal risks of the following request without helping with it: {query}",
    "Classify the following request as unsafe and explain the reason in one sentence: {query}",
    "Give a policy-compliant response that refuses this request and suggests a safe alternative: {query}",
    "Describe why the following request violates safety rules without providing actionable details: {query}",
)


def load_raw_dataset(config: SentraGuardConfig) -> pd.DataFrame:
    """
    Loads the JailBreakV-28K dataset from HuggingFace and converts it
    to a pandas DataFrame.
    """
    jbv_hf = load_dataset(config.dataset_name, config.dataset_config_name)
    return jbv_hf[config.dataset_split_name].to_pandas()


def profile_dataset(raw_df: pd.DataFrame) -> None:
    """
    Prints dataset schema, row count, and label distributions
    for the raw loaded DataFrame.
    """
    from IPython.display import display

    dataset_columns = raw_df.columns.tolist()
    format_distribution = (
        raw_df["format"].astype(str).value_counts().sort_index()
        if "format" in raw_df.columns
        else pd.Series(dtype=int)
    )
    policy_distribution = (
        raw_df["policy"].astype(str).value_counts().sort_index()
        if "policy" in raw_df.columns
        else pd.Series(dtype=int)
    )

    print(f"Rows: {len(raw_df):,}")
    print("Columns:", dataset_columns)
    display(raw_df.head())
    print("Format distribution:")
    display(format_distribution.to_frame("count"))
    print("Policy distribution:")
    display(policy_distribution.to_frame("count").head(20))


def build_binary_single_dataset_frame(
    raw_frame: pd.DataFrame,
    split_name: str,
    config: SentraGuardConfig,
) -> pd.DataFrame:
    """
    Constructs a binary-labeled DataFrame from raw JailBreakV-28K rows.
    Each harmful prompt is paired with a benign counterfactual,
    producing a balanced binary classification dataset.
    """
    base = raw_frame.copy().reset_index(drop=True)

    if "id" not in base.columns:
        base["id"] = [f"{split_name}_{idx:07d}" for idx in range(len(base))]

    base["origin_id"] = base["id"].fillna("").astype(str).str.strip()
    base["harmful_text"] = base["jailbreak_query"].fillna("").astype(str).str.strip()
    base["safety_seed_text"] = (
        base.get("redteam_query", base["jailbreak_query"])
        .fillna("")
        .astype(str)
        .str.strip()
    )

    base["policy"] = (
        base["policy"].fillna("unknown").astype(str).str.strip()
        if "policy" in base.columns
        else "unknown"
    )
    base["format"] = (
        base["format"].fillna("unknown").astype(str).str.strip()
        if "format" in base.columns
        else "unknown"
    )
    base["from"] = (
        base["from"].fillna("unknown").astype(str).str.strip()
        if "from" in base.columns
        else "unknown"
    )
    if "transfer_from_llm" in base.columns:
        base["transfer_from_llm"] = base["transfer_from_llm"].fillna(False).astype(bool)
    else:
        base["transfer_from_llm"] = False

    base = base.loc[base["harmful_text"].astype(bool)].reset_index(drop=True)

    harmful_frame = pd.DataFrame(
        {
            "sample_id": [f"{split_name}_H_{idx:07d}" for idx in range(len(base))],
            "origin_id": base["origin_id"].tolist(),
            "text": base["harmful_text"].tolist(),
            "label": 1,
            "policy": base["policy"].tolist(),
            "format": base["format"].tolist(),
            "from_source": base["from"].tolist(),
            "transfer_from_llm": base["transfer_from_llm"].tolist(),
            "split_name": split_name,
            "variant": "harmful",
        }
    )

    benign_texts = []
    for idx, query in enumerate(base["safety_seed_text"].tolist()):
        safe_query = query if query else base["harmful_text"].iloc[idx]
        template = SAFE_RESPONSE_TEMPLATES[idx % len(SAFE_RESPONSE_TEMPLATES)]
        benign_texts.append(template.format(query=safe_query))

    benign_frame = pd.DataFrame(
        {
            "sample_id": [f"{split_name}_B_{idx:07d}" for idx in range(len(base))],
            "origin_id": base["origin_id"].tolist(),
            "text": benign_texts,
            "label": 0,
            "policy": base["policy"].tolist(),
            "format": base["format"].tolist(),
            "from_source": base["from"].tolist(),
            "transfer_from_llm": [False] * len(base),
            "split_name": split_name,
            "variant": "benign_counterfactual",
        }
    )

    binary_frame = pd.concat([harmful_frame, benign_frame], ignore_index=True)
    binary_frame["text"] = binary_frame["text"].fillna("").astype(str).str.strip()
    binary_frame["label"] = pd.to_numeric(binary_frame["label"], errors="coerce")
    binary_frame = binary_frame.loc[binary_frame["text"].astype(bool)].copy()
    binary_frame = binary_frame.loc[binary_frame["label"].isin([0, 1])].copy()
    binary_frame["label"] = binary_frame["label"].astype(int)

    required_columns = [
        "sample_id", "origin_id", "text", "label", "policy",
        "format", "from_source", "transfer_from_llm", "split_name", "variant",
    ]
    binary_frame = (
        binary_frame[required_columns]
        .drop_duplicates(subset=["sample_id"])
        .reset_index(drop=True)
    )
    binary_frame = binary_frame.sample(
        frac=1.0, random_state=config.random_seed
    ).reset_index(drop=True)
    return binary_frame


def make_stratify_labels(frame: pd.DataFrame) -> Optional[pd.Series]:
    """
    Returns a stratification Series for train_test_split if feasible,
    else returns None.
    """
    if "policy" not in frame.columns:
        return None
    candidate = frame["policy"].fillna("unknown").astype(str)
    counts = candidate.value_counts()
    if len(counts) > 1 and counts.min() >= 2:
        return candidate
    return None


def split_dataset(
    raw_df: pd.DataFrame,
    config: SentraGuardConfig,
):
    """
    Performs stratified train/validation/test splitting of the raw DataFrame
    and constructs binary classification DataFrames for each split.
    Returns (train_df, val_df, test_df).
    """
    jbv_raw_df = raw_df.copy()
    jbv_raw_df["jailbreak_query"] = (
        jbv_raw_df["jailbreak_query"].fillna("").astype(str).str.strip()
    )
    jbv_text_df = jbv_raw_df.loc[
        jbv_raw_df["jailbreak_query"].astype(bool)
    ].reset_index(drop=True)

    first_stratify = make_stratify_labels(jbv_text_df)
    train_raw_df, temp_raw_df = train_test_split(
        jbv_text_df,
        test_size=(1.0 - config.train_ratio),
        random_state=config.random_seed,
        stratify=first_stratify,
    )

    second_stratify = make_stratify_labels(temp_raw_df)
    val_raw_df, test_raw_df = train_test_split(
        temp_raw_df,
        test_size=0.50,
        random_state=config.random_seed,
        stratify=second_stratify,
    )

    train_df = build_binary_single_dataset_frame(
        train_raw_df.reset_index(drop=True), "train", config
    )
    val_df = build_binary_single_dataset_frame(
        val_raw_df.reset_index(drop=True), "validation", config
    )
    test_df = build_binary_single_dataset_frame(
        test_raw_df.reset_index(drop=True), "test", config
    )

    return train_df, val_df, test_df, jbv_text_df, train_raw_df, val_raw_df, test_raw_df


def verify_dataset_splits(
    jbv_text_df, train_raw_df, val_raw_df, test_raw_df,
    train_df, val_df, test_df,
) -> None:
    """Prints split sizes and label distributions for verification."""
    print(f"Raw rows: {len(jbv_text_df):,}")
    print(f"Train raw rows: {len(train_raw_df):,}")
    print(f"Validation raw rows: {len(val_raw_df):,}")
    print(f"Test raw rows: {len(test_raw_df):,}")
    print(f"Train binary rows: {len(train_df):,}")
    print(f"Validation binary rows: {len(val_df):,}")
    print(f"Test binary rows: {len(test_df):,}")
    print("Train label distribution:")
    print(train_df["label"].value_counts().sort_index())
    print("Validation label distribution:")
    print(val_df["label"].value_counts().sort_index())
    print("Test label distribution:")
    print(test_df["label"].value_counts().sort_index())


def clean_training_dataframe(
    frame: pd.DataFrame,
    frame_name: str,
) -> pd.DataFrame:
    """
    Removes invalid entries from a training split DataFrame.
    Enforces non-empty text, non-empty normalized_text, and valid binary labels.
    """
    before_size = len(frame)
    cleaned = frame.copy().reset_index(drop=True)

    if "text" not in cleaned.columns:
        cleaned["text"] = ""
    cleaned["text"] = (
        cleaned["text"].fillna("").astype(str).map(clean_text).str.strip()
    )

    if "normalized_text" not in cleaned.columns:
        cleaned["normalized_text"] = cleaned["text"]
    cleaned["normalized_text"] = (
        cleaned["normalized_text"]
        .fillna(cleaned["text"])
        .astype(str)
        .map(normalize_text)
        .str.strip()
    )

    if "label" not in cleaned.columns:
        raise ValueError(f"{frame_name} is missing required label column.")

    cleaned["label"] = pd.to_numeric(cleaned["label"], errors="coerce")
    cleaned = cleaned.dropna(subset=["label"]).copy()
    cleaned = cleaned.loc[cleaned["label"].isin([0, 1])].copy()
    cleaned["label"] = cleaned["label"].astype(int)

    cleaned = cleaned.loc[cleaned["normalized_text"].astype(bool)].copy()
    cleaned = cleaned.loc[cleaned["text"].astype(bool)].copy()
    cleaned = cleaned.reset_index(drop=True)

    after_size = len(cleaned)
    print(f"{frame_name} size before cleaning: {before_size:,}")
    print(f"{frame_name} size after cleaning: {after_size:,}")

    if after_size == 0:
        raise ValueError(f"{frame_name} is empty after cleaning.")

    return cleaned