# -*- coding: utf-8 -*-
"""normalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
preprocessing/normalization.py

Text normalization utilities for Sentra-Guard.
Handles Unicode normalization, control character removal,
whitespace standardization, and prompt format cleaning.
"""

import re
import unicodedata
from typing import Any

import numpy as np


CONTROL_CHAR_RE = re.compile(r"[\u200b-\u200f\u202a-\u202e\u2060\u2066-\u2069]")
MULTISPACE_RE = re.compile(r"\s+")


def clean_text(text: Any) -> str:
    """
    Applies Unicode normalization, control character removal,
    and whitespace collapsing to a raw input string.
    """
    if text is None or (isinstance(text, float) and np.isnan(text)):
        return ""
    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    text = CONTROL_CHAR_RE.sub(" ", text)
    text = text.replace("\x00", " ")
    text = MULTISPACE_RE.sub(" ", text).strip()
    return text


def normalize_text(text: Any) -> str:
    """
    Applies full normalization including system prompt prefix removal
    and leading/trailing artifact stripping.
    """
    text = clean_text(text)
    text = re.sub(
        r"^\s*(system|assistant|developer|tool)\s*:\s*",
        "",
        text,
        flags=re.IGNORECASE,
    )
    text = text.strip("`\"' ")
    text = MULTISPACE_RE.sub(" ", text).strip()
    return text