# -*- coding: utf-8 -*-
"""tokenization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
preprocessing/tokenization.py

Tokenization pipeline for Sentra-Guard.
Provides the PromptDataset class and DataLoader factory functions
for classifier training, validation, and inference.
"""

from typing import Dict, List, Optional, Sequence, Union

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer

from preprocessing.normalization import clean_text, normalize_text
from utils.config import SentraGuardConfig
from utils.seed import build_torch_generator, seed_worker


class PromptDataset(Dataset):
    """
    Tokenized dataset for harmful prompt classification.
    Supports both labeled (training/evaluation) and unlabeled (inference) modes.
    """

    def __init__(
        self,
        texts: Sequence[str],
        labels: Optional[Sequence[int]],
        tokenizer: AutoTokenizer,
        max_length: int,
    ) -> None:
        self.tokenizer = tokenizer
        self.max_length = int(max_length)

        safe_texts = (
            pd.Series(list(texts), dtype="object")
            .fillna("")
            .astype(str)
            .map(clean_text)
            .str.strip()
            .tolist()
        )
        safe_texts = [text if text else "[EMPTY]" for text in safe_texts]
        self.texts = safe_texts

        if labels is None:
            self.labels = None
        else:
            label_series = pd.to_numeric(pd.Series(list(labels)), errors="coerce")
            if label_series.isna().any():
                raise ValueError("PromptDataset received NaN labels.")
            if not label_series.isin([0, 1]).all():
                raise ValueError("PromptDataset received labels outside {0,1}.")
            self.labels = label_series.astype(int).tolist()

        if self.labels is not None and len(self.texts) != len(self.labels):
            raise ValueError("PromptDataset texts and labels length mismatch.")

    def __len__(self) -> int:
        return len(self.texts)

    def __getitem__(self, index: int) -> Dict[str, torch.Tensor]:
        raw_text = self.texts[index]
        encoded = self.tokenizer(
            raw_text,
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt",
        )

        input_ids = encoded["input_ids"].squeeze(0).long()
        attention_mask = encoded["attention_mask"].squeeze(0).long()

        if input_ids.numel() == 0 or attention_mask.numel() == 0:
            raise ValueError(f"Empty tokenized tensors at dataset index {index}.")
        if not torch.isfinite(input_ids.float()).all():
            raise ValueError(f"Non-finite input_ids at dataset index {index}.")
        if not torch.isfinite(attention_mask.float()).all():
            raise ValueError(f"Non-finite attention_mask at dataset index {index}.")
        if attention_mask.sum().item() <= 0:
            raise ValueError(f"All-zero attention mask at dataset index {index}.")

        item: Dict[str, Union[torch.Tensor, str]] = {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "raw_text": raw_text,
        }

        if self.labels is not None:
            label_value = int(self.labels[index])
            if label_value not in (0, 1):
                raise ValueError(f"Invalid label {label_value} at dataset index {index}.")
            item["labels"] = torch.tensor(label_value, dtype=torch.long)

        return item


def build_text_only_dataloader(
    frame: pd.DataFrame,
    tokenizer: AutoTokenizer,
    config: SentraGuardConfig,
    shuffle: bool,
    batch_size: int = 8,
) -> DataLoader:
    """
    Builds a DataLoader using the raw 'text' column.
    Used for training loop iterations during classifier training.
    """
    safe_frame = frame.copy().reset_index(drop=True)
    safe_frame["text"] = (
        safe_frame["text"].fillna("").astype(str).map(clean_text).str.strip()
    )
    safe_frame["label"] = pd.to_numeric(safe_frame["label"], errors="coerce")
    safe_frame = safe_frame.loc[safe_frame["text"].astype(bool)].copy()
    safe_frame = safe_frame.loc[safe_frame["label"].isin([0, 1])].copy()
    safe_frame["label"] = safe_frame["label"].astype(int)
    safe_frame = safe_frame.reset_index(drop=True)

    if safe_frame.empty:
        raise ValueError("Cannot build DataLoader from empty frame.")

    dataset = PromptDataset(
        texts=safe_frame["text"].tolist(),
        labels=safe_frame["label"].tolist(),
        tokenizer=tokenizer,
        max_length=config.max_length,
    )

    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available(),
        worker_init_fn=seed_worker,
        generator=build_torch_generator(config.random_seed),
    )


def build_prompt_dataloader(
    frame: pd.DataFrame,
    tokenizer: AutoTokenizer,
    config: SentraGuardConfig,
    shuffle: bool,
    batch_size: int = 8,
) -> DataLoader:
    """
    Builds a DataLoader using the 'normalized_text' column.
    Used for normalized multilingual prompt batching.
    """
    safe_frame = frame.copy().reset_index(drop=True)
    safe_frame["normalized_text"] = (
        safe_frame["normalized_text"].fillna("").astype(str).map(normalize_text)
    )
    safe_frame["label"] = pd.to_numeric(safe_frame["label"], errors="coerce")
    safe_frame = safe_frame.loc[safe_frame["label"].isin([0, 1])].copy()
    safe_frame["label"] = safe_frame["label"].astype(int)
    safe_frame = (
        safe_frame.loc[safe_frame["normalized_text"].astype(bool)]
        .copy()
        .reset_index(drop=True)
    )

    if safe_frame.empty:
        raise ValueError("Cannot build DataLoader from an empty dataframe.")

    dataset = PromptDataset(
        texts=safe_frame["normalized_text"].tolist(),
        labels=safe_frame["label"].tolist(),
        tokenizer=tokenizer,
        max_length=config.max_length,
    )

    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available(),
        worker_init_fn=seed_worker,
        generator=build_torch_generator(config.random_seed),
    )