# -*- coding: utf-8 -*-
"""translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
preprocessing/translation.py

Multilingual translation pipeline for Sentra-Guard.
Detects source language and normalizes non-English prompts
to English using Helsinki-NLP Marian MT models.
"""

import warnings
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import torch
from langdetect import DetectorFactory, LangDetectException, detect
from transformers import MarianMTModel, MarianTokenizer

from preprocessing.normalization import normalize_text
from utils.config import SentraGuardConfig

warnings.filterwarnings("ignore")


LANGUAGE_ALIASES = {
    "en": "en", "english": "en",
    "fr": "fr", "french": "fr",
    "es": "es", "spanish": "es",
    "ar": "ar", "arabic": "ar",
    "hi": "hi", "hindi": "hi",
    "bn": "bn", "bengali": "bn",
    "zh": "zh", "chinese": "zh",
}


def canonicalize_language(language: Optional[str]) -> str:
    """Maps raw language codes or names to canonical two-letter codes."""
    if language is None:
        return "unknown"
    language = str(language).strip().lower()
    return LANGUAGE_ALIASES.get(
        language,
        language.split("-")[0] if language else "unknown",
    )


def detect_language_safe(text: str) -> str:
    """
    Detects the source language of a text string.
    Falls back to 'unknown' on detection failures.
    Treats high-ASCII-ratio text as English without invoking langdetect.
    """
    text = normalize_text(text)
    if not text:
        return "unknown"
    ascii_letters = sum(
        char.isascii() and (char.isalpha() or char.isspace())
        for char in text[:512]
    )
    sample_length = max(len(text[:512]), 1)
    if (ascii_letters / sample_length) >= 0.85:
        return "en"
    try:
        return canonicalize_language(detect(text[:512]))
    except LangDetectException:
        return "unknown"


class TranslationManager:
    """
    Manages Marian MT model loading and batch translation
    for multilingual prompt normalization.
    """

    def __init__(
        self,
        model_map: Dict[str, str],
        device: str,
        batch_size: int = 16,
    ) -> None:
        self.model_map = model_map
        self.device = device
        self.batch_size = batch_size
        self.model_cache: Dict[str, MarianMTModel] = {}
        self.tokenizer_cache: Dict[str, MarianTokenizer] = {}

    def _load_model(
        self, source_lang: str
    ) -> Tuple[MarianTokenizer, MarianMTModel]:
        model_name = self.model_map[source_lang]
        if source_lang not in self.model_cache:
            tokenizer = MarianTokenizer.from_pretrained(model_name)
            model = MarianMTModel.from_pretrained(model_name).to(self.device)
            model.eval()
            self.tokenizer_cache[source_lang] = tokenizer
            self.model_cache[source_lang] = model
        return self.tokenizer_cache[source_lang], self.model_cache[source_lang]

    @torch.inference_mode()
    def translate_batch(
        self,
        texts: Sequence[str],
        source_lang: str,
    ) -> List[str]:
        """
        Translates a batch of texts from source_lang to English.
        Returns the original texts if the language is English
        or not in the model map.
        """
        safe_texts = [normalize_text(text) for text in texts]
        if source_lang == "en" or source_lang not in self.model_map:
            return safe_texts

        tokenizer, model = self._load_model(source_lang)
        translated_texts: List[str] = []

        for start in range(0, len(safe_texts), self.batch_size):
            batch = safe_texts[start: start + self.batch_size]
            encoded = tokenizer(
                batch,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=256,
            )
            encoded = {key: value.to(self.device) for key, value in encoded.items()}
            generated = model.generate(**encoded, max_length=256, num_beams=4)
            translated_texts.extend(
                tokenizer.batch_decode(generated, skip_special_tokens=True)
            )

        return [normalize_text(text) for text in translated_texts]


def build_translator_manager(config: SentraGuardConfig) -> TranslationManager:
    """Instantiates the TranslationManager from config."""
    return TranslationManager(
        model_map=config.translation_models,
        device=config.device,
        batch_size=config.translation_batch_size,
    )


def translate_to_english(
    text: str,
    translator_manager: TranslationManager,
    config: SentraGuardConfig,
    source_lang: Optional[str] = None,
) -> str:
    """
    Normalizes and translates a single text string to English.
    Detects the source language automatically if not provided.
    """
    normalized = normalize_text(text)
    if not normalized:
        return ""
    detected_language = (
        canonicalize_language(source_lang)
        if source_lang
        else detect_language_safe(normalized)
    )
    translated = translator_manager.translate_batch([normalized], detected_language)[0]
    return normalize_text(translated)


def preprocess_text(
    text: str,
    translator_manager: TranslationManager,
    config: SentraGuardConfig,
    source_lang: Optional[str] = None,
) -> Dict[str, str]:
    """
    Runs the full single-sample normalization and translation pipeline.
    Returns a dict with clean_text, normalized_text, detected_language,
    and normalization_status.
    """
    normalized_source_text = normalize_text(text)
    if not normalized_source_text:
        return {
            "clean_text": "",
            "normalized_text": "",
            "detected_language": "unknown",
            "normalization_status": "empty",
        }

    detected_language = (
        canonicalize_language(source_lang)
        if source_lang
        else detect_language_safe(normalized_source_text)
    )

    if detected_language == "en":
        translated_text = normalized_source_text
        status = "english_pass"
    elif detected_language in config.translation_models:
        translated_text = translate_to_english(
            normalized_source_text, translator_manager, config, detected_language
        )
        status = "translated"
    else:
        translated_text = normalized_source_text
        status = "translation_unavailable"

    return {
        "clean_text": normalized_source_text,
        "normalized_text": normalize_text(translated_text),
        "detected_language": detected_language,
        "normalization_status": status,
    }


def preprocess_dataframe(
    frame: pd.DataFrame,
    translator_manager: TranslationManager,
    config: SentraGuardConfig,
) -> pd.DataFrame:
    """
    Applies the full normalization and translation pipeline to a DataFrame.
    Adds normalized_text, detected_language, and normalization_status columns.
    Removes rows with empty text or invalid labels.
    """
    processed = frame.copy().reset_index(drop=True)
    processed["text"] = processed["text"].fillna("").astype(str).map(normalize_text)

    if "label" in processed.columns:
        processed["label"] = pd.to_numeric(processed["label"], errors="coerce")
        processed = processed.loc[processed["label"].isin([0, 1])].copy()
        processed["label"] = processed["label"].astype(int)

    processed = (
        processed.loc[processed["text"].astype(bool)]
        .copy()
        .reset_index(drop=True)
    )
    if processed.empty:
        raise ValueError(
            "All rows were removed during preprocessing; no valid text rows remain."
        )

    unique_texts = processed["text"].dropna().astype(str).unique().tolist()
    language_map = {
        text: detect_language_safe(text) if text else "unknown"
        for text in unique_texts
    }

    translated_map: Dict[str, str] = {}
    status_map: Dict[str, str] = {}
    grouped: Dict[str, List[str]] = {}

    for text, language in language_map.items():
        grouped.setdefault(language, []).append(text)

    for language, texts in grouped.items():
        if language == "en":
            for text in texts:
                translated_map[text] = text
                status_map[text] = "english_pass"
        elif language in config.translation_models:
            translated_texts = translator_manager.translate_batch(texts, language)
            for original, translated in zip(texts, translated_texts):
                safe_translated = normalize_text(translated)
                translated_map[original] = (
                    safe_translated if safe_translated else original
                )
                status_map[original] = "translated"
        else:
            for text in texts:
                translated_map[text] = text
                status_map[text] = "translation_unavailable"

    processed["detected_language"] = processed["text"].map(language_map)
    processed["normalized_text"] = (
        processed["text"].map(translated_map).fillna("")
    )
    processed["normalized_text"] = (
        processed["normalized_text"].astype(str).map(normalize_text)
    )
    processed["normalization_status"] = (
        processed["text"].map(status_map).fillna("unknown")
    )

    processed = (
        processed.loc[processed["normalized_text"].astype(bool)]
        .copy()
        .reset_index(drop=True)
    )

    if "label" in processed.columns:
        processed = (
            processed.loc[processed["label"].isin([0, 1])]
            .copy()
            .reset_index(drop=True)
        )
        processed["label"] = processed["label"].astype(int)

    if processed.empty:
        raise ValueError(
            "All rows were removed after normalization; "
            "no valid normalized_text rows remain."
        )

    return processed