# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
utils/config.py

Sentra-Guard runtime configuration.
All hyperparameters, model identifiers, dataset settings,
and path configurations are centralized here.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import torch


@dataclass
class SentraGuardConfig:
    random_seed: int = 42
    device: str = field(default_factory=lambda: "cuda" if torch.cuda.is_available() else "cpu")

    batch_size: int = 8
    epochs: int = 5
    learning_rate: float = 2e-5
    weight_decay: float = 0.01
    warmup_ratio: float = 0.10
    max_length: int = 256
    early_stopping_patience: int = 2
    max_grad_norm: float = 1.0
    classifier_dropout: float = 0.15

    classifier_backend: str = "deberta"
    classifier_model_name: str = "microsoft/deberta-v3-base"
    fallback_classifier_model_name: str = "distilbert-base-uncased"
    zero_shot_model_name: str = "facebook/bart-large-mnli"
    retrieval_model_name: str = "sentence-transformers/all-mpnet-base-v2"

    fusion_weights: Tuple[float, float, float] = (0.50, 0.25, 0.25)
    threshold: float = 0.50
    top_k: int = 5
    uncertainty_margin: float = 0.08

    train_ratio: float = 0.80
    validation_ratio: float = 0.10
    test_ratio: float = 0.10

    use_focal_loss: bool = True
    focal_gamma: float = 2.0
    use_hard_negatives: bool = True
    hard_negative_ratio: float = 0.50
    hard_negative_max_samples: int = 2000

    embedding_batch_size: int = 128
    zero_shot_batch_size: int = 8
    translation_batch_size: int = 16

    threshold_grid: Tuple[float, ...] = tuple(np.round(np.arange(0.05, 0.96, 0.05), 2))
    weight_grid_step: float = 0.10

    dataset_name: str = "JailbreakV-28K/JailBreakV-28k"
    dataset_config_name: str = "JailBreakV_28K"
    dataset_split_name: str = "JailBreakV_28K"

    output_dir: str = "/content/sentra_guard_jbv_artifacts"

    translation_models: Dict[str, str] = field(
        default_factory=lambda: {
            "fr": "Helsinki-NLP/opus-mt-fr-en",
            "es": "Helsinki-NLP/opus-mt-es-en",
            "ar": "Helsinki-NLP/opus-mt-ar-en",
            "hi": "Helsinki-NLP/opus-mt-hi-en",
            "bn": "Helsinki-NLP/opus-mt-bn-en",
            "zh": "Helsinki-NLP/opus-mt-zh-en",
        }
    )

    def resolve_classifier_model_name(self) -> str:
        backend = self.classifier_backend.strip().lower()
        if backend == "deberta":
            return "microsoft/deberta-v3-base"
        if backend == "distilbert":
            return self.fallback_classifier_model_name
        raise ValueError(f"Unsupported classifier backend: {self.classifier_backend}")


def build_config() -> SentraGuardConfig:
    """Instantiates and resolves the Sentra-Guard runtime configuration."""
    config = SentraGuardConfig()
    config.classifier_model_name = config.resolve_classifier_model_name()
    config.device = "cuda" if torch.cuda.is_available() else "cpu"
    return config


def build_artifact_paths(config: SentraGuardConfig):
    """
    Creates and returns the primary artifact directory paths.
    Returns a dict with keys: artifact_dir, checkpoint_dir, retrieval_dir, export_dir.
    """
    artifact_dir = Path(config.output_dir)
    checkpoint_dir = artifact_dir / "checkpoints"
    retrieval_dir = artifact_dir / "retrieval"
    export_dir = artifact_dir / "exports"

    for path in (artifact_dir, checkpoint_dir, retrieval_dir, export_dir):
        path.mkdir(parents=True, exist_ok=True)

    return {
        "artifact_dir": artifact_dir,
        "checkpoint_dir": checkpoint_dir,
        "retrieval_dir": retrieval_dir,
        "export_dir": export_dir,
    }