# -*- coding: utf-8 -*-
"""helpers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
utils/helpers.py

Shared utility functions for Sentra-Guard.
Covers tensor state validation, NaN detection, and DataFrame helpers.
"""

from typing import Any, Dict, List, Optional, Sequence

import numpy as np
import pandas as pd
import torch
import torch.nn as nn


def _get_text_series(frame: pd.DataFrame) -> pd.Series:
    """Extracts and sanitizes the text column from a DataFrame."""
    if "text" not in frame.columns:
        raise ValueError("Expected a 'text' column in the dataframe.")
    return frame["text"].fillna("").astype(str).str.strip()


def debug_training_state(
    batch: Optional[Dict[str, torch.Tensor]] = None,
    logits: Optional[torch.Tensor] = None,
    loss: Optional[torch.Tensor] = None,
    model: Optional[nn.Module] = None,
    prefix: str = "debug",
) -> bool:
    """
    Validates batch, logits, loss, and gradient tensors for NaN and Inf values.
    Returns True if no issues are detected.
    """
    issues: List[str] = []

    def check_tensor(name: str, tensor: torch.Tensor) -> None:
        if tensor is None:
            return
        if tensor.numel() == 0:
            issues.append(f"{name}: empty")
            return
        tensor_float = tensor.detach().float()
        if torch.isnan(tensor_float).any():
            issues.append(f"{name}: NaN")
        if torch.isinf(tensor_float).any():
            issues.append(f"{name}: Inf")

    if batch is not None:
        if "input_ids" in batch:
            check_tensor("input_ids", batch["input_ids"])
        if "attention_mask" in batch:
            check_tensor("attention_mask", batch["attention_mask"])
        if "labels" in batch:
            check_tensor("labels", batch["labels"])
            labels = batch["labels"]
            if (~((labels == 0) | (labels == 1))).any():
                issues.append("labels: invalid values")

    if logits is not None:
        check_tensor("logits", logits)

    if loss is not None:
        check_tensor("loss", loss.view(1))

    if model is not None:
        for name, param in model.named_parameters():
            if param.grad is None:
                continue
            grad = param.grad.detach()
            if grad.numel() == 0:
                continue
            if torch.isnan(grad).any():
                issues.append(f"gradient {name}: NaN")
                break
            if torch.isinf(grad).any():
                issues.append(f"gradient {name}: Inf")
                break

    if issues:
        print(f"[{prefix}] " + " | ".join(issues))
        return False
    return True


def safe_compute_metrics(
    y_true: Sequence[int],
    y_pred: Sequence[int],
) -> Dict[str, float]:
    """
    Computes accuracy, precision, recall, and F1 with NaN-safe input handling.
    """
    from sklearn.metrics import accuracy_score, precision_recall_fscore_support

    y_true_series = pd.to_numeric(pd.Series(list(y_true)), errors="coerce")
    y_pred_series = pd.to_numeric(pd.Series(list(y_pred)), errors="coerce")

    valid_mask = (
        y_true_series.notna()
        & y_pred_series.notna()
        & y_true_series.isin([0, 1])
        & y_pred_series.isin([0, 1])
    )

    y_true_clean = y_true_series.loc[valid_mask].astype(int).to_numpy()
    y_pred_clean = y_pred_series.loc[valid_mask].astype(int).to_numpy()

    if y_true_clean.size == 0:
        return {"accuracy": 0.0, "precision": 0.0, "recall": 0.0, "f1": 0.0}

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true_clean,
        y_pred_clean,
        average="binary",
        zero_division=0,
    )

    return {
        "accuracy": float(accuracy_score(y_true_clean, y_pred_clean)),
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
    }