# -*- coding: utf-8 -*-
"""metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
utils/metrics.py

Evaluation metric utilities for Sentra-Guard.
Provides safe binary classification metric computation
and structured evaluation report generation.
"""

from typing import Any, Dict, List, Optional, Sequence

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    precision_recall_fscore_support,
    roc_auc_score,
)


def _compute_epoch_metrics(
    y_true: Sequence[int],
    y_pred: Sequence[int],
) -> Dict[str, float]:
    """
    Computes per-epoch classification metrics with NaN-safe input handling.
    Used internally during training and validation loops.
    """
    y_true_series = pd.to_numeric(pd.Series(list(y_true)), errors="coerce")
    y_pred_series = pd.to_numeric(pd.Series(list(y_pred)), errors="coerce")

    valid_mask = (
        y_true_series.notna()
        & y_pred_series.notna()
        & y_true_series.isin([0, 1])
        & y_pred_series.isin([0, 1])
    )

    y_true_clean = y_true_series.loc[valid_mask].astype(int).to_numpy()
    y_pred_clean = y_pred_series.loc[valid_mask].astype(int).to_numpy()

    if y_true_clean.size == 0:
        return {"accuracy": 0.0, "precision": 0.0, "recall": 0.0, "f1": 0.0}

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true_clean,
        y_pred_clean,
        average="binary",
        zero_division=0,
    )

    return {
        "accuracy": float(accuracy_score(y_true_clean, y_pred_clean)),
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
    }


def safe_compute_binary_metrics(
    y_true: Sequence[int],
    y_pred: Sequence[int],
    y_score: Optional[Sequence[float]] = None,
) -> Dict[str, Any]:
    """
    Computes full binary classification metrics including ROC-AUC and PR-AUC
    with complete NaN-safe input handling.
    """
    y_true_series = pd.to_numeric(pd.Series(list(y_true)), errors="coerce")
    y_pred_series = pd.to_numeric(pd.Series(list(y_pred)), errors="coerce")

    valid_mask = (
        y_true_series.notna()
        & y_pred_series.notna()
        & y_true_series.isin([0, 1])
        & y_pred_series.isin([0, 1])
    )

    y_true_clean = y_true_series.loc[valid_mask].astype(int).to_numpy()
    y_pred_clean = y_pred_series.loc[valid_mask].astype(int).to_numpy()

    metrics = {
        "accuracy": 0.0,
        "precision": 0.0,
        "recall": 0.0,
        "f1": 0.0,
        "roc_auc": float("nan"),
        "pr_auc": float("nan"),
        "confusion_matrix": [[0, 0], [0, 0]],
    }

    if y_true_clean.size == 0:
        return metrics

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true_clean,
        y_pred_clean,
        average="binary",
        zero_division=0,
    )
    metrics["accuracy"] = float(accuracy_score(y_true_clean, y_pred_clean))
    metrics["precision"] = float(precision)
    metrics["recall"] = float(recall)
    metrics["f1"] = float(f1)
    metrics["confusion_matrix"] = confusion_matrix(
        y_true_clean, y_pred_clean, labels=[0, 1]
    ).tolist()

    if y_score is not None:
        y_score_series = pd.to_numeric(pd.Series(list(y_score)), errors="coerce")
        score_mask = valid_mask & y_score_series.notna()
        y_true_score = y_true_series.loc[score_mask].astype(int).to_numpy()
        y_score_clean = y_score_series.loc[score_mask].astype(float).to_numpy()
        y_score_clean = np.nan_to_num(y_score_clean, nan=0.0, posinf=1.0, neginf=0.0)
        y_score_clean = np.clip(y_score_clean, 0.0, 1.0)

        if len(np.unique(y_true_score)) > 1:
            metrics["roc_auc"] = float(roc_auc_score(y_true_score, y_score_clean))
            metrics["pr_auc"] = float(average_precision_score(y_true_score, y_score_clean))

    return metrics


def build_evaluation_report(
    frame: pd.DataFrame,
    dataset_name: str,
    model_name: str,
    score_column: str,
    pred_column: str,
) -> Dict[str, Any]:
    """
    Builds a structured evaluation report dictionary from a scored DataFrame.
    Used for both Sentra-Guard and baseline model reporting.
    """
    metrics = safe_compute_binary_metrics(
        y_true=frame["label"].tolist(),
        y_pred=frame[pred_column].tolist(),
        y_score=frame[score_column].tolist(),
    )
    return {
        "dataset": dataset_name,
        "model": model_name,
        "n": int(len(frame)),
        "accuracy": metrics["accuracy"],
        "precision": metrics["precision"],
        "recall": metrics["recall"],
        "f1": metrics["f1"],
        "roc_auc": metrics["roc_auc"],
        "pr_auc": metrics["pr_auc"],
        "confusion_matrix": metrics["confusion_matrix"],
    }