# -*- coding: utf-8 -*-
"""seed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
utils/seed.py

Reproducibility utilities for Sentra-Guard.
Configures random seeds and deterministic execution behavior.
"""

import os
import random

import numpy as np
import torch
from langdetect import DetectorFactory

from utils.config import SentraGuardConfig


def set_global_seeds(config: SentraGuardConfig) -> None:
    """Applies all seed settings for reproducible execution."""
    os.environ["PYTHONHASHSEED"] = str(config.random_seed)
    os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")

    random.seed(config.random_seed)
    np.random.seed(config.random_seed)
    torch.manual_seed(config.random_seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(config.random_seed)
        torch.cuda.manual_seed_all(config.random_seed)

    DetectorFactory.seed = config.random_seed
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    try:
        torch.use_deterministic_algorithms(True, warn_only=True)
    except TypeError:
        torch.use_deterministic_algorithms(True)


def build_torch_generator(seed: int) -> torch.Generator:
    """Creates a seeded PyTorch generator for DataLoader reproducibility."""
    generator = torch.Generator()
    generator.manual_seed(seed)
    return generator


def seed_worker(worker_id: int) -> None:
    """DataLoader worker initialization function for reproducible batching."""
    worker_seed = (torch.initial_seed() + worker_id) % (2 ** 32)
    random.seed(worker_seed)
    np.random.seed(worker_seed)