# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
scripts/evaluate.py

Evaluation and ablation pipeline for Sentra-Guard.
Implements baseline model comparisons, full evaluation reports,
and component-level ablation studies.
"""

from typing import Any, Dict, List, Optional, Sequence, Tuple

import faiss
import numpy as np
import pandas as pd
from IPython.display import display
from sentence_transformers import SentenceTransformer
from transformers import AutoModelForSequenceClassification, AutoTokenizer

from models.classifier_model import compute_classifier_scores
from models.zero_shot_model import compute_zero_shot_scores
from scripts.fusion import compute_final_scores
from scripts.inference import score_split
from scripts.retrieval import compute_retrieval_scores
from utils.config import SentraGuardConfig
from utils.helpers import _get_text_series
from utils.metrics import build_evaluation_report, safe_compute_binary_metrics


class StaticKeywordFilter:
    """
    Baseline keyword-based harmful prompt filter.
    Scores prompts by counting matches against a static keyword list.
    """

    def __init__(self) -> None:
        self.keywords = [
            "ignore previous instructions",
            "bypass safety",
            "disable safety",
            "jailbreak",
            "prompt injection",
            "exploit",
            "malware",
            "phishing",
            "weapon",
            "ransomware",
            "steal credentials",
            "how to hack",
            "make a bomb",
            "override policy",
        ]

    def score(self, texts: Sequence[str]) -> np.ndarray:
        safe_texts = [
            str(text).lower().strip() if text is not None else "" for text in texts
        ]
        scores: List[float] = []
        for text in safe_texts:
            match_count = sum(keyword in text for keyword in self.keywords)
            score = min(1.0, match_count / 3.0)
            scores.append(float(score))
        return np.asarray(scores, dtype=np.float32)


def run_zero_shot_only_baseline(
    frame: pd.DataFrame,
    split_name: str,
    zero_shot_classifier,
    config: SentraGuardConfig,
) -> pd.DataFrame:
    """Evaluates the zero-shot-only baseline on a DataFrame split."""
    safe_frame = frame.copy().reset_index(drop=True)
    safe_frame["text"] = _get_text_series(safe_frame)

    zero_scores = compute_zero_shot_scores(
        safe_frame["text"].tolist(),
        zero_shot_classifier=zero_shot_classifier,
        batch_size=config.zero_shot_batch_size,
    )
    pred_label = (zero_scores >= 0.50).astype(int)

    output = safe_frame.copy()
    output["split_name"] = split_name
    output["score"] = zero_scores
    output["pred_label"] = pred_label
    output["pred_label_name"] = np.where(pred_label == 1, "harmful", "benign")
    return output


def run_full_ensemble_baseline(
    frame: pd.DataFrame,
    split_name: str,
    classifier_model: AutoModelForSequenceClassification,
    classifier_tokenizer: AutoTokenizer,
    retrieval_model: SentenceTransformer,
    faiss_index: faiss.IndexFlatIP,
    zero_shot_classifier,
    config: SentraGuardConfig,
) -> pd.DataFrame:
    """
    Evaluates the equal-weight full ensemble baseline (w1=w2=w3=1/3).
    """
    safe_frame = frame.copy().reset_index(drop=True)
    safe_frame["text"] = _get_text_series(safe_frame)

    clf_scores = compute_classifier_scores(
        safe_frame["text"].tolist(), classifier_model, classifier_tokenizer, config
    )
    ret_scores = compute_retrieval_scores(
        safe_frame["text"].tolist(), retrieval_model, faiss_index, config
    )
    zs_scores = compute_zero_shot_scores(
        safe_frame["text"].tolist(), zero_shot_classifier,
        batch_size=config.zero_shot_batch_size,
    )

    ensemble_weights = (1.0 / 3.0, 1.0 / 3.0, 1.0 / 3.0)
    final_scores = compute_final_scores(clf_scores, ret_scores, zs_scores, ensemble_weights)
    pred_label = (final_scores >= 0.50).astype(int)

    output = safe_frame.copy()
    output["split_name"] = split_name
    output["classifier_score"] = clf_scores
    output["retrieval_score"] = ret_scores
    output["zero_shot_score"] = zs_scores
    output["score"] = final_scores
    output["pred_label"] = pred_label
    output["pred_label_name"] = np.where(pred_label == 1, "harmful", "benign")
    return output


def run_ablation_variant(
    frame: pd.DataFrame,
    split_name: str,
    weights: Tuple[float, float, float],
    classifier_model, classifier_tokenizer,
    retrieval_model, faiss_index, zero_shot_classifier,
    config: SentraGuardConfig,
    threshold: Optional[float] = None,
) -> pd.DataFrame:
    """
    Runs one ablation variant with specified fusion weights.
    Used to measure the contribution of each Sentra-Guard component.
    """
    safe_frame = frame.copy().reset_index(drop=True)
    safe_frame["text"] = _get_text_series(safe_frame)

    clf_scores = compute_classifier_scores(
        safe_frame["text"].tolist(), classifier_model, classifier_tokenizer, config
    )
    ret_scores = compute_retrieval_scores(
        safe_frame["text"].tolist(), retrieval_model, faiss_index, config
    )
    zs_scores = compute_zero_shot_scores(
        safe_frame["text"].tolist(), zero_shot_classifier,
        batch_size=config.zero_shot_batch_size,
    )

    final_scores = compute_final_scores(clf_scores, ret_scores, zs_scores, weights)
    threshold = float(config.threshold if threshold is None else threshold)
    pred_label = (final_scores >= threshold).astype(int)

    output = safe_frame.copy()
    output["score"] = final_scores
    output["pred_label"] = pred_label
    output["pred_label_name"] = np.where(pred_label == 1, "harmful", "benign")
    output["split_name"] = split_name
    return output


def run_full_evaluation(
    test_df: pd.DataFrame,
    test_scored: pd.DataFrame,
    classifier_model, classifier_tokenizer,
    retrieval_model, faiss_index, zero_shot_classifier,
    config: SentraGuardConfig,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Runs the full Sentra-Guard evaluation including baselines and ablation study.
    Returns (final_metrics_df, baseline_results_df, ablation_df).
    """
    keyword_filter = StaticKeywordFilter()

    keyword_test_scores = keyword_filter.score(_get_text_series(test_df).tolist())
    keyword_test_df = test_df.copy().reset_index(drop=True)
    keyword_test_df["score"] = keyword_test_scores
    keyword_test_df["pred_label"] = (keyword_test_scores >= 0.50).astype(int)
    keyword_test_df["pred_label_name"] = np.where(
        keyword_test_df["pred_label"] == 1, "harmful", "benign"
    )

    zero_shot_only_test_df = run_zero_shot_only_baseline(
        test_df, "test_zero_shot_only", zero_shot_classifier, config
    )
    full_ensemble_test_df = run_full_ensemble_baseline(
        test_df, "test_full_ensemble",
        classifier_model, classifier_tokenizer,
        retrieval_model, faiss_index, zero_shot_classifier, config,
    )

    sentra_guard_report = build_evaluation_report(
        test_scored, "test_df", "Sentra-Guard", "final_score", "pred_label"
    )
    keyword_report = build_evaluation_report(
        keyword_test_df, "test_df", "Static Keyword Filter", "score", "pred_label"
    )
    zero_shot_only_report = build_evaluation_report(
        zero_shot_only_test_df, "test_df", "Zero-shot Only", "score", "pred_label"
    )
    full_ensemble_report = build_evaluation_report(
        full_ensemble_test_df, "test_df", "Full Ensemble", "score", "pred_label"
    )

    baseline_results_df = pd.DataFrame(
        [keyword_report, zero_shot_only_report, full_ensemble_report]
    )
    final_metrics_df = pd.DataFrame([sentra_guard_report])

    ablation_specs = {
        "without_classifier": (0.0, 0.5, 0.5),
        "without_retrieval": (0.5, 0.0, 0.5),
        "without_zero_shot": (0.5, 0.5, 0.0),
    }
    ablation_rows: List[Dict[str, Any]] = []
    for ablation_name, ablation_weights in ablation_specs.items():
        ablation_df_variant = run_ablation_variant(
            test_df, split_name=ablation_name,
            weights=ablation_weights,
            classifier_model=classifier_model,
            classifier_tokenizer=classifier_tokenizer,
            retrieval_model=retrieval_model,
            faiss_index=faiss_index,
            zero_shot_classifier=zero_shot_classifier,
            config=config,
            threshold=config.threshold,
        )
        report = build_evaluation_report(
            ablation_df_variant, "test_df", ablation_name, "score", "pred_label"
        )
        report["w1"] = float(ablation_weights[0])
        report["w2"] = float(ablation_weights[1])
        report["w3"] = float(ablation_weights[2])
        ablation_rows.append(report)

    ablation_df = pd.DataFrame(ablation_rows)

    display(final_metrics_df)
    display(baseline_results_df)
    display(ablation_df)

    return final_metrics_df, baseline_results_df, ablation_df