# -*- coding: utf-8 -*-
"""fusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
scripts/fusion.py

Hybrid risk fusion for Sentra-Guard.
Combines classifier, retrieval, and zero-shot scores
into a single weighted harmfulness score.
"""

from typing import Sequence, Tuple, Union

import numpy as np


def compute_final_scores(
    classifier_scores: Union[Sequence[float], np.ndarray],
    retrieval_scores: Union[Sequence[float], np.ndarray],
    zero_shot_scores: Union[Sequence[float], np.ndarray],
    weights: Tuple[float, float, float],
) -> np.ndarray:
    """
    Fuses three harmfulness signal sources into a single risk score.
    Applies weighted linear combination and clips the result to [0, 1].
    """
    classifier_scores = np.asarray(classifier_scores, dtype=np.float32)
    retrieval_scores = np.asarray(retrieval_scores, dtype=np.float32)
    zero_shot_scores = np.asarray(zero_shot_scores, dtype=np.float32)

    if not (classifier_scores.shape == retrieval_scores.shape == zero_shot_scores.shape):
        raise ValueError("All score arrays must have the same shape.")

    if len(weights) != 3:
        raise ValueError("Fusion weights must contain exactly three values.")

    w1, w2, w3 = [float(weight) for weight in weights]
    final_scores = (
        (w1 * classifier_scores)
        + (w2 * retrieval_scores)
        + (w3 * zero_shot_scores)
    )
    final_scores = np.nan_to_num(final_scores, nan=0.0, posinf=1.0, neginf=0.0)
    final_scores = np.clip(final_scores, 0.0, 1.0).astype(np.float32)
    return final_scores