# -*- coding: utf-8 -*-
"""hitl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
scripts/hitl.py

Human-in-the-loop adaptive memory update pipeline for Sentra-Guard.
Adds newly confirmed harmful prompts to the FAISS retrieval index
and expands the adversarial memory corpus.
"""

from typing import Dict, Sequence

import faiss
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

from models.retrieval_model import encode_texts_for_retrieval
from utils.config import SentraGuardConfig


def update_adversarial_memory(
    new_harmful_prompts: Sequence[str],
    retrieval_corpus_df: pd.DataFrame,
    retrieval_corpus_embeddings: np.ndarray,
    retrieval_index_embeddings: np.ndarray,
    faiss_index: faiss.IndexFlatIP,
    retrieval_model: SentenceTransformer,
) -> Dict:
    """
    Adds newly confirmed harmful prompts to the adversarial memory bank.
    Updates the FAISS index, corpus DataFrame, and embedding arrays in place.
    Returns a dict with the updated objects and the count of added samples.
    """
    safe_texts = [
        str(text).strip() if text is not None else "" for text in new_harmful_prompts
    ]
    safe_texts = [text for text in safe_texts if text]

    if len(safe_texts) == 0:
        return {
            "retrieval_corpus_df": retrieval_corpus_df,
            "retrieval_corpus_embeddings": retrieval_corpus_embeddings,
            "retrieval_index_embeddings": retrieval_index_embeddings,
            "faiss_index": faiss_index,
            "added_count": 0,
        }

    new_embeddings = encode_texts_for_retrieval(
        safe_texts,
        retrieval_model=retrieval_model,
        batch_size=64,
        normalize_embeddings=False,
        show_progress_bar=False,
    )
    new_embeddings = np.ascontiguousarray(new_embeddings.astype(np.float32))
    faiss.normalize_L2(new_embeddings)

    faiss_index.add(new_embeddings)

    new_rows = pd.DataFrame(
        {"text": safe_texts, "label": 1, "source": "hitl_memory"}
    )
    retrieval_corpus_df = pd.concat(
        [retrieval_corpus_df, new_rows], ignore_index=True
    )
    retrieval_corpus_embeddings = np.vstack(
        [retrieval_corpus_embeddings, new_embeddings.astype(np.float32)]
    )
    retrieval_index_embeddings = np.vstack(
        [retrieval_index_embeddings, new_embeddings.astype(np.float32)]
    )

    return {
        "retrieval_corpus_df": retrieval_corpus_df,
        "retrieval_corpus_embeddings": retrieval_corpus_embeddings,
        "retrieval_index_embeddings": retrieval_index_embeddings,
        "faiss_index": faiss_index,
        "added_count": len(safe_texts),
    }