# -*- coding: utf-8 -*-
"""retrieval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
scripts/retrieval.py

FAISS-based semantic retrieval pipeline for Sentra-Guard.
Builds the adversarial memory corpus, constructs the FAISS index,
and computes similarity-based harmfulness scores.
"""

from typing import Optional, Sequence, Tuple

import faiss
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

from models.retrieval_model import encode_texts_for_retrieval
from utils.config import SentraGuardConfig
from utils.helpers import _get_text_series


def build_retrieval_corpus(
    train_df: pd.DataFrame,
    retrieval_model: SentenceTransformer,
    config: SentraGuardConfig,
) -> Tuple[pd.DataFrame, np.ndarray]:
    """
    Constructs the retrieval corpus from harmful training samples.
    Encodes all harmful prompts into dense embeddings.
    Returns (retrieval_corpus_df, retrieval_corpus_embeddings).
    """
    retrieval_corpus_df = (
        train_df.loc[train_df["label"].astype(int) == 1]
        .copy()
        .reset_index(drop=True)
    )
    retrieval_corpus_df["text"] = _get_text_series(retrieval_corpus_df)
    retrieval_corpus_df = retrieval_corpus_df.loc[
        retrieval_corpus_df["text"].astype(bool)
    ].reset_index(drop=True)

    if retrieval_corpus_df.empty:
        raise ValueError(
            "No harmful prompts available in train_df for retrieval corpus construction."
        )

    retrieval_corpus_embeddings = encode_texts_for_retrieval(
        retrieval_corpus_df["text"].tolist(),
        retrieval_model=retrieval_model,
        batch_size=64,
        normalize_embeddings=False,
        show_progress_bar=True,
    )

    print(f"Retrieval corpus size: {len(retrieval_corpus_df):,}")
    print(f"Retrieval embedding shape: {retrieval_corpus_embeddings.shape}")
    return retrieval_corpus_df, retrieval_corpus_embeddings


def build_faiss_index(
    retrieval_corpus_embeddings: np.ndarray,
) -> Tuple[faiss.IndexFlatIP, np.ndarray]:
    """
    Constructs a FAISS inner-product index from normalized corpus embeddings.
    Returns (faiss_index, retrieval_index_embeddings).
    """
    retrieval_index_embeddings = np.ascontiguousarray(
        retrieval_corpus_embeddings.astype(np.float32).copy()
    )
    faiss.normalize_L2(retrieval_index_embeddings)

    faiss_index = faiss.IndexFlatIP(retrieval_index_embeddings.shape[1])
    faiss_index.add(retrieval_index_embeddings)

    print(f"FAISS index size: {faiss_index.ntotal:,}")
    print(f"Embedding dimension: {retrieval_index_embeddings.shape[1]}")
    return faiss_index, retrieval_index_embeddings


def compute_retrieval_scores(
    texts: Sequence[str],
    retrieval_model: SentenceTransformer,
    faiss_index: faiss.IndexFlatIP,
    config: SentraGuardConfig,
    top_k: Optional[int] = None,
) -> np.ndarray:
    """
    Computes FAISS-based semantic similarity scores for a sequence of texts.
    Scores are averaged over top-k nearest neighbors and mapped to [0, 1].
    """
    safe_texts = [str(text).strip() if text is not None else "" for text in texts]
    if len(safe_texts) == 0:
        return np.asarray([], dtype=np.float32)

    query_embeddings = encode_texts_for_retrieval(
        safe_texts,
        retrieval_model=retrieval_model,
        batch_size=64,
        normalize_embeddings=False,
        show_progress_bar=False,
    )
    query_embeddings = np.ascontiguousarray(query_embeddings.astype(np.float32))
    faiss.normalize_L2(query_embeddings)

    k = int(top_k or getattr(config, "top_k", 5))
    k = max(1, min(k, faiss_index.ntotal))

    similarities, _ = faiss_index.search(query_embeddings, k)
    similarities = np.asarray(similarities, dtype=np.float32)

    scaled_similarities = np.clip((similarities + 1.0) / 2.0, 0.0, 1.0)
    retrieval_scores = scaled_similarities.mean(axis=1)
    retrieval_scores = np.nan_to_num(
        retrieval_scores, nan=0.0, posinf=1.0, neginf=0.0
    )
    retrieval_scores = np.clip(retrieval_scores, 0.0, 1.0).astype(np.float32)
    return retrieval_scores