# -*- coding: utf-8 -*-
"""thresholding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
scripts/thresholding.py

Threshold and fusion weight optimization for Sentra-Guard.
Performs grid search over decision thresholds and weight combinations
using validation set F1 as the selection criterion.
"""

from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from IPython.display import display

from scripts.fusion import compute_final_scores
from utils.config import SentraGuardConfig
from utils.metrics import safe_compute_binary_metrics


def optimize_threshold(
    val_classifier_scores: np.ndarray,
    val_retrieval_scores: np.ndarray,
    val_zero_shot_scores: np.ndarray,
    val_labels: List[int],
    config: SentraGuardConfig,
) -> Tuple[float, pd.DataFrame]:
    """
    Performs a grid search over the threshold range to find the threshold
    that maximizes F1 on the validation set using default fusion weights.
    Returns (best_threshold, threshold_search_df).
    """
    val_default_final_scores = compute_final_scores(
        val_classifier_scores,
        val_retrieval_scores,
        val_zero_shot_scores,
        tuple(config.fusion_weights),
    )

    threshold_search_rows: List[Dict[str, Any]] = []
    best_threshold = 0.50
    best_threshold_f1 = -1.0

    for threshold_value in np.round(np.arange(0.05, 1.00, 0.05), 2):
        val_pred = (val_default_final_scores >= threshold_value).astype(int)
        metrics = safe_compute_binary_metrics(
            val_labels,
            val_pred.tolist(),
            val_default_final_scores.tolist(),
        )
        row = {
            "threshold": float(threshold_value),
            "accuracy": metrics["accuracy"],
            "precision": metrics["precision"],
            "recall": metrics["recall"],
            "f1": metrics["f1"],
            "roc_auc": metrics["roc_auc"],
            "pr_auc": metrics["pr_auc"],
        }
        threshold_search_rows.append(row)

        if metrics["f1"] > best_threshold_f1:
            best_threshold_f1 = float(metrics["f1"])
            best_threshold = float(threshold_value)

    threshold_search_df = pd.DataFrame(threshold_search_rows).sort_values(
        by=["f1", "recall", "precision", "threshold"],
        ascending=[False, False, False, True],
    ).reset_index(drop=True)

    config.threshold = float(best_threshold)
    print(f"Best threshold: {config.threshold}")
    display(threshold_search_df.head(10))
    return best_threshold, threshold_search_df


def generate_weight_grid(step: float = 0.1) -> List[Tuple[float, float, float]]:
    """
    Generates all valid (w1, w2, w3) combinations that sum to 1.0
    within the given step resolution.
    """
    values = np.round(np.arange(0.0, 1.0 + step, step), 2)
    grid: List[Tuple[float, float, float]] = []

    for w1 in values:
        for w2 in values:
            w3 = round(1.0 - w1 - w2, 2)
            if w3 < 0.0 or w3 > 1.0:
                continue
            if abs((w1 + w2 + w3) - 1.0) > 1e-8:
                continue
            grid.append((float(w1), float(w2), float(w3)))

    return sorted(set(grid))


def optimize_fusion_weights(
    val_classifier_scores: np.ndarray,
    val_retrieval_scores: np.ndarray,
    val_zero_shot_scores: np.ndarray,
    val_labels: List[int],
    config: SentraGuardConfig,
) -> Tuple[Tuple[float, float, float], float, pd.DataFrame]:
    """
    Joint grid search over fusion weights and decision thresholds
    to maximize validation F1.
    Returns (best_weights, best_threshold, weight_search_df).
    """
    weight_search_rows: List[Dict[str, Any]] = []
    best_weights = tuple(config.fusion_weights)
    best_weight_f1 = -1.0
    best_weight_threshold = float(config.threshold)

    for weights in generate_weight_grid(step=config.weight_grid_step):
        fused_scores = compute_final_scores(
            val_classifier_scores,
            val_retrieval_scores,
            val_zero_shot_scores,
            weights,
        )
        for threshold_value in np.round(np.arange(0.05, 1.00, 0.05), 2):
            val_pred = (fused_scores >= threshold_value).astype(int)
            metrics = safe_compute_binary_metrics(
                val_labels,
                val_pred.tolist(),
                fused_scores.tolist(),
            )
            row = {
                "w1": float(weights[0]),
                "w2": float(weights[1]),
                "w3": float(weights[2]),
                "threshold": float(threshold_value),
                "accuracy": metrics["accuracy"],
                "precision": metrics["precision"],
                "recall": metrics["recall"],
                "f1": metrics["f1"],
                "roc_auc": metrics["roc_auc"],
                "pr_auc": metrics["pr_auc"],
            }
            weight_search_rows.append(row)

            if metrics["f1"] > best_weight_f1:
                best_weight_f1 = float(metrics["f1"])
                best_weights = tuple(weights)
                best_weight_threshold = float(threshold_value)

    weight_search_df = pd.DataFrame(weight_search_rows).sort_values(
        by=["f1", "recall", "precision", "threshold"],
        ascending=[False, False, False, True],
    ).reset_index(drop=True)

    config.fusion_weights = tuple(best_weights)
    config.threshold = float(best_weight_threshold)

    print(f"Best fusion weights: {config.fusion_weights}")
    print(f"Best threshold after joint search: {config.threshold}")
    display(weight_search_df.head(10))
    return best_weights, best_weight_threshold, weight_search_df