# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
scripts/train.py

Transformer classifier training pipeline for Sentra-Guard.
Implements class-weighted loss, AdamW optimization,
linear warmup scheduling, training/validation loops,
early stopping, and best-checkpoint saving.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import AdamW
from torch.utils.data import DataLoader
from tqdm.auto import tqdm
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    get_linear_schedule_with_warmup,
)

from utils.config import SentraGuardConfig
from utils.metrics import _compute_epoch_metrics


def compute_class_weights(
    labels: Sequence[int],
    device: str,
    eps: float = 1e-8,
) -> torch.Tensor:
    """
    Computes inverse-frequency class weights for handling class imbalance.
    """
    label_array = pd.to_numeric(pd.Series(labels), errors="coerce").to_numpy()
    valid_mask = np.isfinite(label_array) & np.isin(label_array, [0, 1])
    label_array = label_array[valid_mask].astype(np.int64)

    if label_array.size == 0:
        return torch.ones(2, dtype=torch.float32, device=device)

    class_counts = np.bincount(label_array, minlength=2).astype(np.float32)
    class_counts = np.maximum(class_counts, eps)
    class_weights = label_array.shape[0] / (len(class_counts) * class_counts)
    class_weights = np.nan_to_num(class_weights, nan=1.0, posinf=1.0, neginf=1.0)
    class_weights = np.clip(class_weights, eps, None)
    class_weights = class_weights / max(class_weights.mean(), eps)
    return torch.tensor(class_weights, dtype=torch.float32, device=device)


def compute_safe_class_weights(
    labels: Sequence[int],
    device: str,
    eps: float = 1e-8,
) -> torch.Tensor:
    """
    NaN-safe class weight computation with normalization.
    """
    label_array = pd.to_numeric(pd.Series(list(labels)), errors="coerce").to_numpy()
    valid_mask = np.isfinite(label_array) & np.isin(label_array, [0, 1])
    label_array = label_array[valid_mask].astype(np.int64)

    if label_array.size == 0:
        return torch.ones(2, dtype=torch.float32, device=device)

    class_counts = np.bincount(label_array, minlength=2).astype(np.float32)
    class_counts = np.maximum(class_counts, eps)
    class_weights = label_array.shape[0] / (len(class_counts) * class_counts)
    class_weights = np.nan_to_num(class_weights, nan=1.0, posinf=1.0, neginf=1.0)
    class_weights = np.clip(class_weights, eps, None)
    class_weights = class_weights / max(class_weights.mean(), eps)
    return torch.tensor(class_weights, dtype=torch.float32, device=device)


class SafeCrossEntropyLoss(nn.Module):
    """
    Cross-entropy loss with class weighting and NaN-safe logit handling.
    """

    def __init__(self, class_weights: torch.Tensor) -> None:
        super().__init__()
        safe_weights = torch.nan_to_num(
            class_weights.detach().float(),
            nan=1.0,
            posinf=1.0,
            neginf=1.0,
        ).clamp(min=1e-6)
        self.register_buffer("class_weights", safe_weights)

    def forward(
        self, logits: torch.Tensor, targets: torch.Tensor
    ) -> torch.Tensor:
        safe_logits = torch.nan_to_num(
            logits.float(),
            nan=0.0,
            posinf=30.0,
            neginf=-30.0,
        )
        safe_targets = targets.long()
        safe_weights = self.class_weights.to(
            device=safe_logits.device, dtype=safe_logits.dtype
        )
        return F.cross_entropy(safe_logits, safe_targets, weight=safe_weights)


def _print_invalid_batch_state(
    batch: Dict[str, Any],
    logits: Optional[torch.Tensor] = None,
    loss: Optional[torch.Tensor] = None,
) -> None:
    print("Batch texts:")
    print(batch.get("raw_text", []))
    print("Batch input_ids:")
    print(batch["input_ids"].detach().cpu())
    print("Batch labels:")
    print(batch["labels"].detach().cpu())
    if logits is not None:
        print("Batch logits:")
        print(logits.detach().cpu())
    if loss is not None:
        print("Batch loss:")
        print(loss.detach().cpu())


def build_optimizer_and_scheduler(
    model: AutoModelForSequenceClassification,
    train_loader: DataLoader,
    config: SentraGuardConfig,
):
    """
    Initializes AdamW optimizer and linear warmup scheduler.
    Returns (optimizer, scheduler, total_steps, warmup_steps).
    """
    optimizer = AdamW(
        model.parameters(),
        lr=config.learning_rate,
        weight_decay=config.weight_decay,
    )
    total_steps = max(1, len(train_loader) * config.epochs)
    warmup_steps = int(total_steps * config.warmup_ratio)
    warmup_steps = min(warmup_steps, max(total_steps - 1, 0))

    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=total_steps,
    )

    print(f"Total steps: {total_steps}")
    print(f"Warmup steps: {warmup_steps}")
    return optimizer, scheduler, total_steps, warmup_steps


def train_epoch(
    model: AutoModelForSequenceClassification,
    dataloader: DataLoader,
    optimizer: AdamW,
    scheduler: Any,
    criterion: nn.Module,
    device: str,
) -> Dict[str, float]:
    """
    Executes one full training epoch.
    Returns a dict of train loss and classification metrics.
    """
    model.train()

    running_losses: List[float] = []
    all_true: List[int] = []
    all_pred: List[int] = []

    for batch_idx, batch in enumerate(tqdm(dataloader, desc="Training", leave=False)):
        raw_text = batch["raw_text"]
        labels = batch["labels"].to(device)
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        assert torch.isfinite(labels.float()).all(), (
            f"Non-finite labels at training batch {batch_idx}"
        )
        assert torch.isfinite(input_ids.float()).all(), (
            f"Non-finite input_ids at training batch {batch_idx}"
        )
        assert torch.isfinite(attention_mask.float()).all(), (
            f"Non-finite attention_mask at training batch {batch_idx}"
        )

        optimizer.zero_grad(set_to_none=True)
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits.float()

        if not torch.isfinite(logits).all():
            _print_invalid_batch_state(
                {"raw_text": raw_text, "input_ids": input_ids, "labels": labels},
                logits=logits,
            )
            raise AssertionError(
                f"Non-finite logits at training batch {batch_idx}"
            )

        loss = criterion(logits, labels)

        if not torch.isfinite(loss):
            _print_invalid_batch_state(
                {"raw_text": raw_text, "input_ids": input_ids, "labels": labels},
                logits=logits,
                loss=loss,
            )
            raise AssertionError(
                f"Non-finite loss at training batch {batch_idx}"
            )

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        running_losses.append(float(loss.item()))
        preds = torch.argmax(logits, dim=-1)
        all_true.extend(labels.detach().cpu().numpy().astype(int).tolist())
        all_pred.extend(preds.detach().cpu().numpy().astype(int).tolist())

    metrics = _compute_epoch_metrics(all_true, all_pred)
    return {
        "train_loss": float(np.mean(running_losses)) if running_losses else 0.0,
        "train_accuracy": metrics["accuracy"],
        "train_precision": metrics["precision"],
        "train_recall": metrics["recall"],
        "train_f1": metrics["f1"],
        "skipped_batches": 0,
    }


@torch.inference_mode()
def validate_epoch(
    model: AutoModelForSequenceClassification,
    dataloader: DataLoader,
    criterion: nn.Module,
    device: str,
) -> Dict[str, float]:
    """
    Executes one full validation epoch.
    Returns a dict of validation loss and classification metrics.
    """
    model.eval()

    running_losses: List[float] = []
    all_true: List[int] = []
    all_pred: List[int] = []

    for batch_idx, batch in enumerate(
        tqdm(dataloader, desc="Validation", leave=False)
    ):
        raw_text = batch["raw_text"]
        labels = batch["labels"].to(device)
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        assert torch.isfinite(labels.float()).all(), (
            f"Non-finite labels at validation batch {batch_idx}"
        )
        assert torch.isfinite(input_ids.float()).all(), (
            f"Non-finite input_ids at validation batch {batch_idx}"
        )
        assert torch.isfinite(attention_mask.float()).all(), (
            f"Non-finite attention_mask at validation batch {batch_idx}"
        )

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits.float()

        if not torch.isfinite(logits).all():
            _print_invalid_batch_state(
                {"raw_text": raw_text, "input_ids": input_ids, "labels": labels},
                logits=logits,
            )
            raise AssertionError(
                f"Non-finite logits at validation batch {batch_idx}"
            )

        loss = criterion(logits, labels)

        if not torch.isfinite(loss):
            _print_invalid_batch_state(
                {"raw_text": raw_text, "input_ids": input_ids, "labels": labels},
                logits=logits,
                loss=loss,
            )
            raise AssertionError(
                f"Non-finite loss at validation batch {batch_idx}"
            )

        running_losses.append(float(loss.item()))
        preds = torch.argmax(logits, dim=-1)
        all_true.extend(labels.detach().cpu().numpy().astype(int).tolist())
        all_pred.extend(preds.detach().cpu().numpy().astype(int).tolist())

    metrics = _compute_epoch_metrics(all_true, all_pred)
    return {
        "val_loss": float(np.mean(running_losses)) if running_losses else 0.0,
        "val_accuracy": metrics["accuracy"],
        "val_precision": metrics["precision"],
        "val_recall": metrics["recall"],
        "val_f1": metrics["f1"],
        "skipped_batches": 0,
    }


def run_training_loop(
    model: AutoModelForSequenceClassification,
    tokenizer: AutoTokenizer,
    train_loader: DataLoader,
    val_loader: DataLoader,
    criterion: nn.Module,
    optimizer: AdamW,
    scheduler: Any,
    config: SentraGuardConfig,
    checkpoint_dir: Path,
) -> tuple:
    """
    Runs the full training loop with early stopping and best-checkpoint saving.
    Returns (trained_model, training_history_df).
    """
    from IPython.display import display

    best_val_f1 = -1.0
    early_stop_counter = 0
    best_state_dict = None
    training_history: List[Dict[str, float]] = []

    for epoch in range(1, config.epochs + 1):
        train_metrics = train_epoch(
            model, train_loader, optimizer, scheduler, criterion, config.device
        )
        val_metrics = validate_epoch(model, val_loader, criterion, config.device)

        epoch_row = {"epoch": epoch, **train_metrics, **val_metrics}
        training_history.append(epoch_row)

        print(
            f"Epoch {epoch} | "
            f"train_loss={epoch_row['train_loss']:.4f} | "
            f"train_acc={epoch_row['train_accuracy']:.4f} | "
            f"train_prec={epoch_row['train_precision']:.4f} | "
            f"train_rec={epoch_row['train_recall']:.4f} | "
            f"train_f1={epoch_row['train_f1']:.4f} | "
            f"val_loss={epoch_row['val_loss']:.4f} | "
            f"val_acc={epoch_row['val_accuracy']:.4f} | "
            f"val_prec={epoch_row['val_precision']:.4f} | "
            f"val_rec={epoch_row['val_recall']:.4f} | "
            f"val_f1={epoch_row['val_f1']:.4f} | "
            f"train_skipped={epoch_row['skipped_batches']} | "
            f"val_skipped={val_metrics['skipped_batches']}"
        )

        if epoch_row["val_f1"] > best_val_f1:
            best_val_f1 = epoch_row["val_f1"]
            early_stop_counter = 0
            best_state_dict = {
                key: value.detach().cpu().clone()
                for key, value in model.state_dict().items()
            }
            (checkpoint_dir / "classifier").mkdir(parents=True, exist_ok=True)
            model.save_pretrained(checkpoint_dir / "classifier")
            tokenizer.save_pretrained(checkpoint_dir / "classifier")
        else:
            early_stop_counter += 1
            if early_stop_counter >= config.early_stopping_patience:
                print(f"Early stopping triggered at epoch {epoch}")
                break

    if best_state_dict is not None:
        model.load_state_dict(best_state_dict)

    model.to(config.device)
    model.eval()

    training_history_df = pd.DataFrame(training_history)
    display(training_history_df)
    return model, training_history_df