# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
scripts/visualization.py

Visualization pipeline for Sentra-Guard.
Generates training curves, ROC curve, PR curve, and confusion matrix plots.
"""

from typing import Any, Dict

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import precision_recall_curve, roc_curve


def plot_confusion_matrix(
    confusion_matrix_data: Any,
    title: str = "Sentra-Guard Confusion Matrix",
) -> None:
    """Plots the confusion matrix as an annotated heatmap."""
    cm = np.asarray(confusion_matrix_data, dtype=int)
    plt.figure(figsize=(6, 5))
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        cmap="Blues",
        xticklabels=["Benign", "Harmful"],
        yticklabels=["Benign", "Harmful"],
    )
    plt.title(title)
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.tight_layout()
    plt.show()


def plot_training_and_evaluation_curves(
    training_history_df: pd.DataFrame,
    test_scored: pd.DataFrame,
) -> None:
    """
    Plots the training loss curve, precision-recall curve, and ROC curve
    in a single 1x3 figure.
    """
    y_true_curve = np.asarray(test_scored["label"].tolist(), dtype=np.int32)
    y_score_curve = np.asarray(test_scored["final_score"].tolist(), dtype=np.float32)

    precision_curve, recall_curve, _ = precision_recall_curve(
        y_true_curve, y_score_curve
    )
    fpr_curve, tpr_curve, _ = roc_curve(y_true_curve, y_score_curve)

    fig, axes = plt.subplots(1, 3, figsize=(20, 5))

    axes[0].plot(
        training_history_df["epoch"],
        training_history_df["train_loss"],
        marker="o",
        label="Train Loss",
    )
    axes[0].plot(
        training_history_df["epoch"],
        training_history_df["val_loss"],
        marker="o",
        label="Validation Loss",
    )
    axes[0].set_title("Training Curve")
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Loss")
    axes[0].legend()
    axes[0].grid(alpha=0.3)

    axes[1].plot(recall_curve, precision_curve, color="darkorange", linewidth=2)
    axes[1].set_title("Precision-Recall Curve")
    axes[1].set_xlabel("Recall")
    axes[1].set_ylabel("Precision")
    axes[1].grid(alpha=0.3)

    axes[2].plot(fpr_curve, tpr_curve, color="navy", linewidth=2)
    axes[2].plot([0, 1], [0, 1], linestyle="--", color="gray")
    axes[2].set_title("ROC Curve")
    axes[2].set_xlabel("False Positive Rate")
    axes[2].set_ylabel("True Positive Rate")
    axes[2].grid(alpha=0.3)

    plt.tight_layout()
    plt.show()