# -*- coding: utf-8 -*-
"""confusion_matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
visualizations/confusion_matrix.py

Confusion matrix heatmap visualization for Sentra-Guard.
"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns


def plot_confusion_matrix(
    confusion_matrix_data,
    title: str = "Confusion Matrix",
) -> None:
    cm = np.asarray(confusion_matrix_data, dtype=int)
    plt.figure(figsize=(6, 5))
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        cmap="Blues",
        xticklabels=["Benign", "Harmful"],
        yticklabels=["Benign", "Harmful"],
    )
    plt.title(title)
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.tight_layout()
    plt.show()