# -*- coding: utf-8 -*-
"""heatmap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
visualizations/heatmap.py

Training curve heatmap visualization for Sentra-Guard.
"""

import matplotlib.pyplot as plt
import pandas as pd


def plot_training_curve(training_history_df: pd.DataFrame) -> None:
    plt.figure(figsize=(8, 5))
    plt.plot(
        training_history_df["epoch"],
        training_history_df["train_loss"],
        marker="o",
        label="Train Loss",
    )
    plt.plot(
        training_history_df["epoch"],
        training_history_df["val_loss"],
        marker="o",
        label="Validation Loss",
    )
    plt.title("Training Curve")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()