# -*- coding: utf-8 -*-
"""classifier_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
models/classifier_model.py

Transformer classifier for Sentra-Guard.
Handles model initialization, tokenizer setup,
and inference scoring for harmful prompt detection.
"""

from typing import List, Optional, Sequence

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader
from transformers import (
    AutoConfig,
    AutoModelForSequenceClassification,
    AutoTokenizer,
)

from preprocessing.normalization import normalize_text
from preprocessing.tokenization import PromptDataset
from utils.config import SentraGuardConfig
from utils.helpers import debug_training_state


def build_classifier_tokenizer(config: SentraGuardConfig) -> AutoTokenizer:
    """
    Loads and configures the tokenizer for the classifier backbone.
    Assigns a pad token if the tokenizer does not have one.
    """
    tokenizer = AutoTokenizer.from_pretrained(
        config.classifier_model_name,
        use_fast=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = (
            tokenizer.eos_token
            if tokenizer.eos_token is not None
            else "[PAD]"
        )
    print(f"Tokenizer checkpoint: {config.classifier_model_name}")
    return tokenizer


def build_classifier_model(
    config: SentraGuardConfig,
    tokenizer: AutoTokenizer,
) -> AutoModelForSequenceClassification:
    """
    Loads and configures the transformer classifier backbone.
    Sets binary classification labels and moves the model to the target device.
    """
    model_config = AutoConfig.from_pretrained(config.classifier_model_name)
    model_config.num_labels = 2
    model_config.id2label = {0: "benign", 1: "harmful"}
    model_config.label2id = {"benign": 0, "harmful": 1}
    model_config.problem_type = "single_label_classification"

    model = AutoModelForSequenceClassification.from_pretrained(
        config.classifier_model_name,
        config=model_config,
    )

    if (
        getattr(model.config, "pad_token_id", None) is None
        and tokenizer.pad_token_id is not None
    ):
        model.config.pad_token_id = tokenizer.pad_token_id

    model = model.to(config.device).float()
    print(f"Model checkpoint: {config.classifier_model_name}")
    return model


@torch.inference_mode()
def compute_classifier_scores(
    texts: Sequence[str],
    model: AutoModelForSequenceClassification,
    tokenizer: AutoTokenizer,
    config: SentraGuardConfig,
    batch_size: Optional[int] = None,
) -> np.ndarray:
    """
    Runs the classifier on a sequence of texts and returns
    harmful-class probability scores in [0, 1].
    """
    model.eval()
    batch_size = batch_size or max(config.batch_size, 16)

    safe_texts = [
        normalize_text("" if text is None else text) or "[EMPTY]"
        for text in texts
    ]
    dataset = PromptDataset(
        texts=safe_texts,
        labels=None,
        tokenizer=tokenizer,
        max_length=config.max_length,
    )
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=False,
        drop_last=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available(),
    )

    probabilities: List[np.ndarray] = []

    for batch_idx, batch in enumerate(dataloader):
        batch = {
            key: value.to(config.device)
            for key, value in batch.items()
            if isinstance(value, torch.Tensor)
        }

        if not debug_training_state(
            batch=batch, prefix=f"inference batch {batch_idx} precheck"
        ):
            fallback = np.full(
                batch["input_ids"].shape[0], 0.5, dtype=np.float32
            )
            probabilities.append(fallback)
            continue

        outputs = model(
            input_ids=batch["input_ids"],
            attention_mask=batch["attention_mask"],
        )
        logits = outputs.logits

        if not debug_training_state(
            logits=logits,
            prefix=f"inference batch {batch_idx} logits",
        ):
            fallback = np.full(
                batch["input_ids"].shape[0], 0.5, dtype=np.float32
            )
            probabilities.append(fallback)
            continue

        probs = torch.softmax(logits, dim=-1)[:, 1]
        probs = torch.nan_to_num(
            probs, nan=0.5, posinf=1.0, neginf=0.0
        ).clamp(0.0, 1.0)
        probabilities.append(probs.detach().cpu().numpy().astype(np.float32))

    if not probabilities:
        return np.asarray([], dtype=np.float32)

    return np.concatenate(probabilities).astype(np.float32)