# -*- coding: utf-8 -*-
"""retrieval_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
models/retrieval_model.py

SBERT retrieval encoder for Sentra-Guard.
Generates dense sentence embeddings for semantic memory retrieval
using the sentence-transformers library.
"""

from typing import Optional, Sequence

import numpy as np
from sentence_transformers import SentenceTransformer

from utils.config import SentraGuardConfig


def build_retrieval_model(config: SentraGuardConfig) -> SentenceTransformer:
    """
    Loads the sentence encoder for semantic retrieval.
    """
    retrieval_model = SentenceTransformer(
        config.retrieval_model_name,
        device=config.device,
    )
    print(f"Retrieval encoder: {config.retrieval_model_name}")
    return retrieval_model


def encode_texts_for_retrieval(
    texts: Sequence[str],
    retrieval_model: SentenceTransformer,
    batch_size: Optional[int] = None,
    normalize_embeddings: bool = False,
    show_progress_bar: bool = False,
) -> np.ndarray:
    """
    Encodes a sequence of texts into dense float32 embeddings.
    Returns a 2D numpy array of shape (n_texts, embedding_dim).
    """
    safe_texts = [
        str(text).strip() if text is not None else "" for text in texts
    ]
    safe_texts = [text if text else "[EMPTY]" for text in safe_texts]

    embeddings = retrieval_model.encode(
        safe_texts,
        batch_size=batch_size or 64,
        show_progress_bar=show_progress_bar,
        convert_to_numpy=True,
        normalize_embeddings=normalize_embeddings,
    )
    embeddings = np.asarray(embeddings, dtype=np.float32)
    if embeddings.ndim != 2:
        raise ValueError("Retrieval embeddings must be a 2D numpy array.")
    return embeddings