# -*- coding: utf-8 -*-
"""zero_shot_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHKjRjpQsCb6tYh5umwheHwhtdQTqPiI
"""

#!/usr/bin/env python3
"""
models/zero_shot_model.py

Zero-shot NLI inference model for Sentra-Guard.
Computes harmfulness probabilities using BART-large-MNLI
without requiring task-specific fine-tuning.
"""

from typing import List, Sequence

import numpy as np
import torch
from transformers import pipeline

from utils.config import SentraGuardConfig


ZERO_SHOT_CANDIDATE_LABELS = ["harmful", "benign"]


def build_zero_shot_classifier(config: SentraGuardConfig):
    """
    Loads the zero-shot NLI classifier pipeline.
    Assigns to GPU if available, CPU otherwise.
    """
    device_index = (
        0
        if str(config.device).startswith("cuda") and torch.cuda.is_available()
        else -1
    )
    zero_shot_classifier = pipeline(
        "zero-shot-classification",
        model=config.zero_shot_model_name,
        tokenizer=config.zero_shot_model_name,
        device=device_index,
    )
    print(f"Zero-shot model: {config.zero_shot_model_name}")
    return zero_shot_classifier


def compute_zero_shot_scores(
    texts: Sequence[str],
    zero_shot_classifier,
    batch_size: int = 8,
) -> np.ndarray:
    """
    Computes harmful-class probability scores for a sequence of texts
    using zero-shot NLI classification.
    Returns a float32 array of scores in [0, 1].
    """
    safe_texts = [
        str(text).strip() if text is not None else "" for text in texts
    ]
    if len(safe_texts) == 0:
        return np.asarray([], dtype=np.float32)

    outputs: List[float] = []

    for start in range(0, len(safe_texts), batch_size):
        batch_texts = [
            text if text else "[EMPTY]"
            for text in safe_texts[start: start + batch_size]
        ]
        batch_results = zero_shot_classifier(
            batch_texts,
            candidate_labels=ZERO_SHOT_CANDIDATE_LABELS,
            multi_label=False,
            batch_size=batch_size,
        )

        if isinstance(batch_results, dict):
            batch_results = [batch_results]

        for result in batch_results:
            label_score_map = {
                label: float(score)
                for label, score in zip(result["labels"], result["scores"])
            }
            harmful_score = label_score_map.get("harmful", 0.0)
            harmful_score = float(
                np.clip(
                    np.nan_to_num(harmful_score, nan=0.0, posinf=1.0, neginf=0.0),
                    0.0,
                    1.0,
                )
            )
            outputs.append(harmful_score)

    return np.asarray(outputs, dtype=np.float32)